unpackaged/main/default/objects/Campaign/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>Address</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Booked_Tickets__c.field-meta.xml
<CustomField>
    <fullName>Booked_Tickets__c</fullName>
    <label>Booked Tickets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Filled_Volunteer_jobs__c.field-meta.xml
<CustomField>
    <fullName>Filled_Volunteer_jobs__c</fullName>
    <label>Filled Volunteer jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Open_Volunteer_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Open_Volunteer_Jobs__c</fullName>
    <formula>Total_Volunteer_Jobs__c - Filled_Volunteer_jobs__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Open Volunteer Jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Remaining_Tickets__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Tickets__c</fullName>
    <formula>Total_Tickets__c -  Booked_Tickets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Tickets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Total_Tickets__c.field-meta.xml
<CustomField>
    <fullName>Total_Tickets__c</fullName>
    <label>Total Tickets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Total_Volunteer_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Total_Volunteer_Jobs__c</fullName>
    <label>Total Volunteer Jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Type_of_the_Event__c.field-meta.xml
<CustomField>
    <fullName>Type_of_the_Event__c</fullName>
    <label>Type of the Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Volunteer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CampaignController.cls
/* Developer - Jereen Fathima .K
Purpose - To get the Campaign Detail and display on the site
*/
public without sharing class CampaignController {
    @AuraEnabled(cacheable=true)
    public static List<Campaign> getCampaigns(Id contactId) {
        // Retrieve the RecordTypeId of the provided Contact
         RecordType communityMemberRecordType = [
            SELECT Id 
            FROM RecordType 
            WHERE SObjectType = 'Contact'
            LIMIT 1
        ];
        Contact contact = [SELECT RecordTypeId FROM Contact WHERE Id = :contactId LIMIT 1];
      if (contact.RecordTypeId == communityMemberRecordType.Id) {
          system.debug('communityRecord');
            
       return [SELECT Id, Name, Total_Tickets__c, Booked_Tickets__c, Remaining_Tickets__c,
                       Total_Volunteer_Jobs__c, Filled_Volunteer_jobs__c, Open_Volunteer_Jobs__c,
                       StartDate, EndDate,Description, Address__c,CampaignImageId
                FROM Campaign where Type_of_the_Event__c = 'Community'
                ];
        }
       return [SELECT Id, Name, Total_Tickets__c, Booked_Tickets__c, Remaining_Tickets__c,
                       Total_Volunteer_Jobs__c, Filled_Volunteer_jobs__c, Open_Volunteer_Jobs__c,
                       StartDate, EndDate, CampaignImageId,Description, Address__c
                FROM Campaign
                ];
    }
}
/*
    8@AuraEnabled(cacheable=true)
    public static List<Campaign> getCampaigns() {
        return [SELECT Id, Name, Total_Tickets__c, Booked_Tickets__c, Remaining_Tickets__c,
                       Total_Volunteer_Jobs__c, Filled_Volunteer_jobs__c, Open_Volunteer_Jobs__c,
                       StartDate, EndDate, CampaignImageId 
                FROM Campaign
                ]; // Fetch active campaigns
    }*/

/*public with sharing class CampaignController {
    @AuraEnabled(cacheable=true)
    public static List<Campaign> getCampaigns() {
        return [SELECT Id, Name, Total_Tickets__c, Booked_Tickets__c, Remaining_Tickets__c,
                       Total_Volunteer_Jobs__c, Filled_Volunteer_jobs__c, Open_Volunteer_Jobs__c,
                       StartDate, EndDate, CampaignImageId 
                FROM Campaign
                ]; // Fetch active campaigns
    }
}*/