unpackaged/main/default/objects/Volunteer__c/Volunteer__c.object-meta.xml
<CustomObject>
    <description>Object to store Volunteer information for Rise Together Charity Organization.</description>
    <label>Volunteer</label>
    <nameField>
        <displayFormat>Vol-{yyyy}-{0000}</displayFormat>
        <label>Volunteer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Volunteer__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Volunteer Record Approval status</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Volunteer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To capture User Email Address</description>
    <inlineHelpText>Please Enter your Valid Email address</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Volunteer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>To Capture User First name</description>
    <label>First Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Volunteer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>To capture User Last Name</description>
    <label>Last Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Volunteer__c/fields/Volunteer_Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Approver_Comments__c</fullName>
    <label>Volunteer Approver Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Volunteer__c/fields/Volunteer_Status__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Status__c</fullName>
    <label>Volunteer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
        <default>true</default>
        <label>Inactive</label>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/VolunteerController.cls
// --       Projct - NPSP - Sprint2   
//---       Purpose - Added for Volunteer Status Display
//--        Developer - Sophia A    
//-------------------------------------------------------------------------------------------
 
global without sharing class VolunteerController {
          
    @AuraEnabled
    global static Volunteer__c getVolunteerByEmail(String email) {
        List<Volunteer__c> volunteerList =  [SELECT First_Name__c, Last_Name__c, Volunteer_Status__c, Approval_Status__c, Volunteer_Approver_Comments__c 
                FROM Volunteer__c 
                WHERE Email__c = :email 
                LIMIT 1];
        
        // If no volunteer is found, return null
        if (!volunteerList.isEmpty()) {
            return volunteerList[0];
        } else {
            return null;
    }
    }
    
    @AuraEnabled
    global static void createVolunteer(Volunteer__c volunteerData) {
        if (volunteerData == null) {
            throw new AuraHandledException('Volunteer data is required.');
        }

        // Additional checks and logic for the volunteerData
        insert volunteerData;
    }
}