unpackaged/main/default/objects/Community_Member__c/Community_Member__c.object-meta.xml
<CustomObject>
    <description>Object to store community member information for Rise Together Charity Organization.</description>
    <label>Community Member</label>
    <nameField>
        <displayFormat>CM-{yyyy}-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Member__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Record approval status</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Member__c/fields/CommMember_Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>CommMember_Approver_Comments__c</fullName>
    <description>Stores comments from the approver regarding the Community Member record</description>
    <label>CommMember Approver Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Community_Member__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Captures User Email Id</description>
    <inlineHelpText>Please enter your Email (Example@Gmail.com)</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Community_Member__c/fields/Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Member_Status__c</fullName>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
        <default>true</default>
        <label>Inactive</label>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CommunityMemberController.cls
//--------------Community Member Registration Form--------
//Developer ---Sophia A.
//Project - NPSP- Sprint1 & 2
//Purpose -  To check the uniqueness of Email and to Fetch Member Details using Email
// --------------------------------------------------

global without sharing class CommunityMemberController
{
//----NPSP --- Added For Sprint1
    @AuraEnabled
    global static Boolean isEmailUnique(String email) {
        List<Community_Member__c> existingMembers = [SELECT Id FROM Community_Member__c WHERE Email__c = :email LIMIT 1];
        return existingMembers.isEmpty();  
    }
//---NPSP ---- Added For Sprint2
    @AuraEnabled
    global static Community_Member__c getMemberByEmail(String email) {
        List<Community_Member__c> memberList = [
            SELECT First_Name__c, Last_Name__c, Member_Status__c, Approval_Status__c, CommMember_Approver_Comments__c 
            FROM Community_Member__c 
            WHERE Email__c = :email 
            LIMIT 1
        ];
        
        // If no member is found, return null
        if (!memberList.isEmpty()) {
            return memberList[0];
        } else {
            return null;
        }
    }

}