unpackaged/main/default/objects/Community_Member__c/Community_Member__c.object-meta.xml
<CustomObject>
    <description>Object to store community member information for Rise Together Charity Organization.</description>
    <label>Community Member</label>
    <nameField>
        <displayFormat>CM-{yyyy}-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Community_Member__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Record approval status</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Member__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Captures User Email Id</description>
    <inlineHelpText>Please enter your Email (Example@Gmail.com)</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Community_Member__c/fields/Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Member_Status__c</fullName>
    <label>Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Community_Member__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Captures username from the user</description>
    <inlineHelpText>Enter a valid username &amp; it should be in the email format (e.g., user@example.com). This can also be the same as your email address. It must be unique and will serve as your login identifier.</inlineHelpText>
    <label>Username</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
        <default>true</default>
        <label>Inactive</label>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CommunityMemberWelcomeEmailUtility.cls
// *** @Author : Bhargavi
// *** @Project : RiseTogether
// *** @Date : 08/oct/2024
// *** Purpose : To send Welcome email to Community Members

public class CommunityMemberWelcomeEmailUtility {
    public static void sendWelcomeEmail(List<Community_member__c> newMembers){
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for (Community_Member__c communityMember : newMembers){
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            //Set Email Address of Recepients
            email.setToAddresses(new List<string> {communityMember.Email__c});
            //Use Custom Labels for Email Subject and body
            String subject = Label.Community_Member_Welcome_Email_Subject;
            String body = Label.Community_Member_Welcome_Email_Header.replace('{0}', communityMember.Last_Name__c) + '<br>' + '<br>'+
                Label.Community_Member_Welcome_Email_Body.replace ('{0}',communityMember.Name)
                //.replace('{1}',communityMember.Username__c)
                .replace ('{2}',communityMember.Approval_Status__c)
                .replace('{3}', communityMember.Member_Status__c);
            //Assign Email Subject and body
            email.setSubject(subject);
            email.setHtmlBody(body);
            //Add email to the list 'emails'
            emails.add(email);
        }
        //send all emails
        if (!emails.isEmpty()){
            Messaging.sendEmail(emails);   
        }      
    }    
}